# *********************************************************************
#
#  Unix Makefile for examples (use  GNU make)
#
# ********************************************************************

release:
	@echo "This example has to be compiled using Cmake"

clean: release