# *********************************************************************
#
#  Unix Makefile for examples (use  GNU make)
#
# ********************************************************************

release:
	@echo "not supported on unix"

clean: release