# *********************************************************************
#
#  Windows Makefile for examples (use nmake)
# 
# ********************************************************************
.SILENT:

release:
	echo This example has to be compiled using QT Creator

clean: release
